spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${HIKARI_URL}
      username: ${HIKARI_USERNAME}
      password: ${HIKARI_PASSWORD}
      pool-name: hikari-pool
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: ${KAKAO_TYPE}
            scope:
              - ${KAKAO_SCOPE_NICKNAME}
              - ${KAKAO_SCOPE_EMAIL}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.hbm2ddl.auto: update
    # hibernate:
    #  ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

security:
  user:
    name: ${USER_NAME}
    password: ${USER_PASSWORD}

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expirationTime: 86400000 # 1 day
    refreshTokenTime: 604800000 # 7 days

  cookie:
    token:
      key: access_token
      refresh-key: refresh_token
      http-only: true
      secure: true
      domain: together2.netlify.app
      path: /
      max-age: 86400 # 1 day
      refresh-max-age: 604800 # 7 days

openai:
  api:
    key: ${OPENAI_API_KEY}

smartchoice:
  api:
    key: ${SMARTCHOICE_API_KEY}