spring:
  datasource:
    url: jdbc:mysql://localhost:3307/middle_project2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: together
    password: middleproject2
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/middle_project2
      username: together
      password: middleproject2
      pool-name: hikari-pool
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 604b523d970a77490059b67f01f2e05c
            redirect-uri: http://localhost:8080/api/auth/login/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

security:
  user:
    name: together
    password: together


  jwt:
    secret-key: security-1234567890-!@#$%^&*()-security-1234567890
    expirationTime: 86400000 # 1 day
  cookie:
    token:
      key: access_token
      http-only: true
      secure: true
      domain: localhost
      path: /
      max-age: 86400 # 1 day

